export enum MessageType {
	CHAT_MESSAGE = 'CHAT_MESSAGE',
	USER_JOINED = 'USER_JOINED',
	USER_LEFT = 'USER_LEFT',
	CLEAR_CHAT = 'CLEAR_CHAT',
	DELETE_MESSAGE = 'DELETE_MESSAGE',
	TYPING = 'TYPING',
}
